/**
 * Fetch the piece sets and write the stylesheet that selects between them.
 *
 * Run by hand when adding or removing a set, not during a build: the SVGs and
 * the generated CSS are committed, so neither the build nor CI needs the
 * network, and nobody's game depends on lichess being reachable.
 *
 * Only sets whose licence is compatible with this project's GPL-3.0 belong
 * here. Most of lichess's prettier sets are CC BY-NC-SA, whose non-commercial
 * clause is not compatible; see README for the ones that are.
 */
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'public', 'pieces');

/** chessground's role names, keyed by the letter lichess files use. */
const ROLES = { K: 'king', Q: 'queen', R: 'rook', B: 'bishop', N: 'knight', P: 'pawn' };
const COLOURS = { w: 'white', b: 'black' };

const sets = (await readdir(OUT, { withFileTypes: true }))
  .filter(entry => entry.isDirectory())
  .map(entry => entry.name)
  .sort();

const rules = [];
for (const set of sets) {
  for (const [colour, colourName] of Object.entries(COLOURS)) {
    for (const [letter, role] of Object.entries(ROLES)) {
      // Relative to this stylesheet, so it works whatever path the site is
      // served from -- a custom domain at the root or a project page below one.
      rules.push(
        `.cg-wrap.set-${set} piece.${role}.${colourName}{` +
          `background-image:url("../pieces/${set}/${colour}${letter}.svg")}`,
      );
    }
  }
}

await mkdir(dirname(join(ROOT, 'src', 'pieces.css')), { recursive: true });
await writeFile(
  join(ROOT, 'src', 'pieces.css'),
  [
    '/*',
    ' * Generated by scripts/vendor-pieces.mjs. Do not edit.',
    ' *',
    ' * One rule per piece per set. The board carries a set-<name> class, which',
    ' * outranks chessground’s own .cg-wrap piece rules and so replaces the',
    ' * built-in images without touching them.',
    ' */',
    ...rules,
    '',
  ].join('\n'),
);

console.log(`${sets.length} sets, ${rules.length} rules -> src/pieces.css`);
console.log(sets.join(', '));
