/**
 * Write the board colour stylesheet.
 *
 * A board is two colours, so these are written rather than fetched: nothing to
 * download, nobody to credit, no licence to check. chessground paints its own
 * board with one small SVG tile over a background colour and these do the same.
 *
 * Run by hand when adding a theme; the output is committed.
 */
import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** name, light square, dark square, text on light, text on dark. */
const THEMES = [
  ['brown', '#f0d9b5', '#b58863', '#3d2b1f', '#f6e7d0'],
  ['blue', '#dee3e6', '#8ca2ad', '#27343a', '#eef2f4'],
  ['green', '#ffffdd', '#86a666', '#2c3a20', '#f4f7e2'],
  ['grey', '#ececec', '#b8b8b8', '#2e2e2e', '#f7f7f7'],
  ['purple', '#efeff4', '#8877b7', '#2d2340', '#f3f0fa'],
  ['slate', '#cdd5df', '#64748b', '#1e293b', '#f1f5f9'],
];

/**
 * A two-by-two checkerboard, scaled to a quarter of the board so it tiles to
 * eight squares. crispEdges keeps the squares square at any size, where a CSS
 * gradient would soften each join into a grey seam.
 */
const tile = (light, dark) =>
  Buffer.from(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2 2" shape-rendering="crispEdges">' +
      `<rect width="2" height="2" fill="${light}"/>` +
      `<rect width="1" height="1" fill="${dark}"/>` +
      `<rect x="1" y="1" width="1" height="1" fill="${dark}"/>` +
      '</svg>',
  ).toString('base64');

const blocks = THEMES.map(
  ([name, light, dark, onLight, onDark]) => `
.cg-wrap.board-${name} cg-board {
  background-color: ${light};
  background-image: url('data:image/svg+xml;base64,${tile(light, dark)}');
  background-size: 25% 25%;
}

.board-${name} .orientation-white .ranks :nth-child(even),
.board-${name} .orientation-white .files :nth-child(odd),
.board-${name} .orientation-black .ranks :nth-child(odd),
.board-${name} .orientation-black .files :nth-child(even),
.cg-wrap.board-${name} .ranks :nth-child(even),
.cg-wrap.board-${name} .files :nth-child(odd) {
  color: ${onDark};
}

.cg-wrap.board-${name} .ranks :nth-child(odd),
.cg-wrap.board-${name} .files :nth-child(even) {
  color: ${onLight};
}`,
);

await writeFile(
  join(ROOT, 'src', 'boards.css'),
  [
    '/*',
    ' * Generated by scripts/vendor-boards.mjs. Do not edit.',
    ' *',
    ' * A board is two colours. chessground paints its own with one small SVG tile',
    ' * over a background colour, and these do the same: a 2x2 tile scaled to a',
    ' * quarter of the board, with crispEdges so the squares stay square at any size',
    ' * rather than softening into the greys a gradient would give.',
    ' *',
    ' * The coordinate colours travel with each theme, because a number legible on',
    ' * pale wood disappears on slate.',
    ' */',
    ...blocks,
    '',
  ].join('\n'),
);

console.log(`${THEMES.length} board themes -> src/boards.css`);
